#combat
Combat Time In Seconds: '10'
Combat Timer: '&cYou will untagged in &4<time>&c seconds'
Not Combat Tagged: '&cYou''re no longer combat tagged'
Command In Combat: '&cYou cant send commands when you''re combat tagged!'
Enter Safezone In Combat Title: '&4No Entry'
Enter Safezone In Combat Subtitle: '&cYou cant enter safezones while in combat!'

#config
Dirtlands Reloaded: '&aDirtlands Reloaded!'

#commands
No Command Permission: '&cYou dont have permission to use this command!'
Player Only Command: '&cYou must be a player to execute this command!'
Player Doesnt Exist: '&4<player>&c doesn''t exist!'
Player Hasnt Logged In: '&4<player>&c has never logged in before!'
Player Is Offline: '&4<player>&c is offline!'

#input errors
Invalid Number: '&cInvalid number!'

#economy
Money Gained Actionbar: '&3+<money> &bExpensive Diamonds &o(You Have &3<balance>&b)'
Money Set Actionbar: '&bYour Balance Has Been Set To &3<money>'
Money Lost Actionbar: '&3-<money> &bExpensive Diamonds &o(You Have &3<balance>&b)'
Cant Afford Message: '&cYou can''t afford this!'
Player Doesnt Have Enough Money: '&c<player> doesn''t have enough money for this action'
Baltop Header: '<#b8a567>&m----------&r <#7c3e12>Baltop <#b8a567>&m-</#b8a567>&r <#7c3e12>Page</#7c3e12> <#856f2d><page><#7c3e12>/</#7c3e12><pages> <#b8a567>&m----------'
Baltop Names: '<#b8a567>(#<position>) <#856f2d><name>: <#7c3e12><balance>'
Player Balance: '&3<player>&b has &3<balance>&b expensive diamonds'
Balance: '&3You&b have &3<balance>&b expensive diamonds'

#shop
No Space: '&cYou don''t have enough space in your inventory for this'


#word filter
Word Filter: ["Nigger", "Nigga", "Chink", "Coon", "Jap", "Kys", "Kill yourself", "Fag", "Faggot", "Retard", "Retarded"]
Chat Blocked: "&c&lHey! &r&cYour message hasn't been sent due to a blocked word. &4(&c<word>&4)"