name: Dirtlands
version: 1.0
api-version: 1.18
description: Dirt
depend: [WorldGuard, LuckPerms, Citizens, Jeeper-Essentials]
author: Jeeper_
main: net.dirtlands.Main
commands:
  dirtlands:
    description: dirtlands command that branches out to other server-related commands
  economy:
    description: used for giving, removing, and setting money
    aliases: [econ, eco]
  baltop:
    description: gets the top richest players
  bal:
    description: gets the balance of a player
  garp:
    description: warps to the shop
permissions:
  dirtlands.dirtlands:
    description: gives access to server-related commands
    default: op
  dirtlands.economy:
    description: gives access to the /economy command!
    default: op
  dirtlands.shopkeeper:
    description: gives access to editing shopkeepers
    default: op
  dirtlands.combat.bypass:
    description: allows bypassing combat restrictions
    default: op
