name: Dirtlands
version: 1.0
api-version: 1.19
description: Dirt
depend: [WorldGuard, LuckPerms, Citizens, Jeeper-Essentials]
author: Jeeper_
main: net.dirtlands.Main
commands:
  dirtlands:
    description: dirtlands command that branches out to other server-related commands
  garp:
    description: warps to the shop
  playtime:
    description: gets the playtime of a player
  horsemount:
    description: gives the player a horse mount with the specified arguments
    aliases: [horse]
  buy:
    description: edits the lore of an item to make a buy item
  sell:
    description: edits the lore of an item to make a sell item
  carboncopy:
    description: edits the lore of an item to make it a carbon copy
  durability:
    description: adds custom durability to an item
  diamond:
    description: gives the player a diamond
  token:
    description: gives the player a token
permissions:
  dirtlands.dirtlands:
    description: gives access to server-related commands
    default: op
  dirtlands.economy:
    description: gives access to economy-related commands
    default: op
  dirtlands.shopkeeper:
    description: gives access to editing shopkeepers
    default: op
  dirtlands.combat.bypass:
    description: allows bypassing combat restrictions
    default: op
  dirtlands.horsemount:
    description: allows the use of the /horsemount command
    default: op
  dirtlands.durability:
    description: allows players to set custom durability on an item
    default: op